name: Snyk Security Scan

on: [push, pull_request]

jobs:
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk Scan
        run: snyk test --json > snyk-report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Snyk Report
        uses: actions/upload-artifact@v3
        with:
          name: snyk-report
          path: snyk-report.json


